SimpleMobileTools/Simple-Notes

app/src/main/res/layout/activity_main.xml

So app bar doesn't scroll off screen. It's a *huge* QoL improvement. For example, right now you can't select all -> cut/copy because those controls are off the screen.
Note: I made this PR via the github web interface so I've done absolutely zero testing.

add scrollbar to text field

---

app/build.gradle

The commit allows to have debug and release build installed side by side.
Currently it's hard to switch between release and debug build while developing: you need to backup all your notes somewhere one by one, then actually develop, send changes, then install release version again. A couple of weeks passes, you want something to be improved and go through all this mess again. You may ask me why can't I keep debug version installed. Here's why: something may break in an unstable version and cause notes to be lost.

Set applicationIdSuffix to ".debug"

---

app/src/main/res/layout/note_view_horiz_scrollable.xml
app/src/main/res/layout/note_view_static.xml

Implement #217. According to [the documentation](https://developer.android.com/reference/android/view/inputmethod/EditorInfo#IME_FLAG_NO_PERSONALIZED_LEARNING) of the IME_FLAG_NO_PERSONALIZED_LEARNING
> Applications need to be aware that the flag is not a guarantee, and some IMEs may not respect it.
So, it's nice to have, but might not work in some cases.

Disable personalized learning when typing note text

---

app/src/main/res/values-de/strings.xml
app/src/main/res/values/strings.xml

Imho, this change better reflects the intent of the option. I noticed it, because the German translation is incorrect. The translator apparently interpreted the 'undone' as 'reverted' (which can be right but does not fit in this context).

Change the wording of the checklist sorting option

---

app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/MainActivity.kt

Addresses #423.
OutputStream for existing files with `content://` path needs to be opened in truncate mode, its description: "If the file already exists and is a regular file and is opened for writing, it will be truncated to length 0."
Streams for files with `/storage` path don't seem to be affected by this issue and don't need the truncate mode.
See more at https://developer.android.com/reference/android/os/ParcelFileDescriptor#parseMode(java.lang.String).

Fix editing previously exported notes not working properly

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/MainActivity.kt
app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/WidgetConfigureActivity.kt
app/src/main/kotlin/com/simplemobiletools/notes/pro/fragments/ChecklistFragment.kt
app/src/main/kotlin/com/simplemobiletools/notes/pro/fragments/TextFragment.kt
app/src/main/kotlin/com/simplemobiletools/notes/pro/models/Note.kt

- Remove note biometric protection if the biometric id is no longer available. This check is done to avoid the user not being able to unlock the note if they remove the biometric id from phone settings.
- Update commons library version.
- Remove `USE_BIOMETRIC` permission. As far as I can tell, it works without explicitly declaring it, because it's declared in the androidx.biometric library itself.

Remove note protection if biometric id is no longer available

---

app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/MainActivity.kt

Fixes #444.
- Use "rwt" mode instead of "wt" as the "wt" seems to not work with Google Drive.
- A more general fix to not update note info if export failed.

Fix error when exporting notes to Google Drive

---

app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/MainActivity.kt

Hi,
I've changed visibility behavior of undo and redo buttons to avoid problem with jumping undo button as it was described in the issue. You can check on the video below how I've approached it.
Also, while fixing this, I found another bug related to undo/redo buttons - they weren't hiding after creating a new note; I've also fixed it.
**Before:**
https://user-images.githubusercontent.com/85929121/134818281-3c999432-efbf-4242-9f23-d1efc7a8b986.mp4
**After:**
https://user-images.githubusercontent.com/85929121/134818290-e82a72a3-7a74-4249-a0cd-c792bdc181b6.mp4

Changed undo/redo visibility behavior (#427)

---

app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/MainActivity.kt

Hi,
I've fixed a minor bug that the search button wasn't hiding for checklist when the app was launched.
**Before:**
https://user-images.githubusercontent.com/85929121/138551067-a2e80dbd-3207-4a64-aaca-8d3461eec139.mp4
**After:**
https://user-images.githubusercontent.com/85929121/138551079-7ff67a3a-d873-4d84-94d0-c7a21784d852.mp4

Fixed search button not hiding for checklist

---

app/src/main/kotlin/com/simplemobiletools/notes/pro/adapters/ChecklistAdapter.kt

Hi,
When setting custom sorting while moving checklist items, there was a missing setting it for move to top/bottom options. I've added it.
**Before:**
https://user-images.githubusercontent.com/85929121/147935465-e7e53779-5918-4612-b756-03b0116fe362.mp4
**After:**
https://user-images.githubusercontent.com/85929121/147935474-dafa0064-4e3f-49df-bd24-446301346fcc.mp4

Added setting custom sorting on move to top/bottom

---

app/src/main/res/layout/fragment_checklist.xml

Hi,
There's my proposition how to solve the issue that action button hides the last item check. 
- Closes #443. 
- I've added a padding to the recycler view, so the user can scroll a bit more to the top and the last item is fully visible with a bit of space underneath.
- It was the easiest to do and doesn't change too much how the app looks.
**Before:**
https://user-images.githubusercontent.com/85929121/154661150-b34aef59-761d-4c4b-b0b6-e41bab18a3d3.mp4
**After:**
https://user-images.githubusercontent.com/85929121/154661166-4d1a051b-f282-43f7-bb48-f11b393e7dc8.mp4

Added padding for checklist to avoid hiding the last item (#443)

---

app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/MainActivity.kt

Hi,
I've found a bug related to creating notes from shortcuts. After creating such note, if user exit the app by using back button, reverting it back from recents screen was triggering creating note once again. The issue was that intent was being reverted from history, so to fix it, I've added checking intent's flags if it's not from history. Also, to be sure that everything will work fine, I've added removing extras from intent after using them.
**Before:**
https://user-images.githubusercontent.com/85929121/155188634-75156af9-b36c-42b0-952d-a029d1165bc8.mp4
**After:**
https://user-images.githubusercontent.com/85929121/155188718-42217ed9-89ac-415a-a561-3776f2b12548.mp4

Fixed unnecessary note creating on app resume

---

app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/MainActivity.kt
app/src/main/kotlin/com/simplemobiletools/notes/pro/adapters/NotesPagerAdapter.kt
app/src/main/kotlin/com/simplemobiletools/notes/pro/fragments/ChecklistFragment.kt
app/src/main/kotlin/com/simplemobiletools/notes/pro/fragments/NoteFragment.kt
app/src/main/kotlin/com/simplemobiletools/notes/pro/fragments/TextFragment.kt

Hi,
While working on all notes export/import, I've found out, that synchronization of checklists wasn't working at all, despite that the option was visible. I've added it fully, both on export and import.
Details:
- I'm reusing save logic for notes in checklists (moved it to more common place).
- Moved reading checklists from directly reading value from DB to helper that also reads from file.
- Also moved code related to note updates to NoteFragment, not to be invoked just for text notes.
- Added the same null-checks before saving checklist as there are for notes.
https://user-images.githubusercontent.com/85929121/155588847-bd365d25-ba07-4909-a18e-992b79a72df8.mp4

Added synchronization to checklist export and import

---

app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/MainActivity.kt
app/src/main/kotlin/com/simplemobiletools/notes/pro/fragments/NoteFragment.kt

Hi,
I've noticed that toast about successful export wasn't always showing the proper note title. Here's a fix for this. Also, I've noticed that in one case toast was displayed despite the option to not show it, so I've added a condition.
**Before:**
https://user-images.githubusercontent.com/85929121/157256189-3e71977e-e58e-473b-bb58-6af1683288ac.mp4
**After:**
https://user-images.githubusercontent.com/85929121/157256358-309a49f9-5b7c-4bc0-b90d-ecf3e8bbadf8.mp4

Fixed wrong title in export toast

---

app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/MainActivity.kt
app/src/main/kotlin/com/simplemobiletools/notes/pro/helpers/NotesImporter.kt

If the no exported JSON notes are found in the file, the file is treated as a simple text file like before

Parse exported JSON notes when opening files

---

app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/MainActivity.kt

- fixes #621
- hotfix causing the issue implemented in 1741070686d83745762bf285455aac985f10fca1
- for further explanation read [this comment](https://github.com/SimpleMobileTools/Simple-Notes/issues/621#issuecomment-1555908584)
Tested on Android 13 (SDK 33, LineageOS `20-20230410-microG-FP4`) on a Fairphone 4
It might be that the change in line 246 is not required because `MyMovementMethod` might not trigger the issue fixed by this workaround. But because I cannot test this, I want to make sure that the workaround is still in place *if* that is the case.

Use MyMovementMethod on hotfix fixing crash on selection (SDK<=23)

---

app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/SettingsActivity.kt
app/src/main/kotlin/com/simplemobiletools/notes/pro/adapters/WidgetAdapter.kt
app/src/main/kotlin/com/simplemobiletools/notes/pro/helpers/Config.kt
app/src/main/kotlin/com/simplemobiletools/notes/pro/helpers/Constants.kt

Replaces `Left` and `Right` gravity with the proper `Start` and `End` equivalents to support RTL languages.
Fixes #353: Aligning RTL text isn't working correctly.
Before the change, notes and checklists in the app were aligned to one side, either Left or Right (regardless of LTR or RTL of the language). This was inconsistent with the widgets, which were already using Start and End gravity (`widget_text_layout.xml`).
After the change to Start / End, both LTR and RTL languages can coexist in the same note / checklist.
The Alignment setting should not be needed anymore for RTL as it works out of the box. It still uses the Left & Right terms for simplicity and even swaps the labels for RTL languages. TBD if renaming them to something like "Default" and "Inverted" would make more sense.

Fix 353: Change gravity internally from Left and Right to Start and End

---

app/build.gradle
app/src/main/kotlin/com/simplemobiletools/notes/pro/adapters/WidgetAdapter.kt

There are 2 known issues with this update:
- Max font scaling does not look well in the PagerTabStrip
- Not sure if caused by the update, updating file linked to the note sometimes fails with SecurityException
No other changes from these lists affects this app:
- https://developer.android.com/about/versions/14/behavior-changes-all
- https://developer.android.com/about/versions/14/behavior-changes-14
This also fixes a crash when widget checklist is empty.

Update targetSdkVersion to 34

---

app/src/main/kotlin/com/simplemobiletools/notes/pro/helpers/CollatorBasedComparator.kt
app/src/main/kotlin/com/simplemobiletools/notes/pro/models/ChecklistItem.kt

Fixes #615 'Checklist - Order issue with char like É or È' by using a locale-aware Collator.

Fix #615: Use a locale-aware Collator for sorting Checklists

---

app/src/main/kotlin/com/simplemobiletools/notes/pro/fragments/TextFragment.kt

`onViewStateRestored()` in TextFragment crashed with `ClassCastException`, because layout has `MyEditText` with id `text_note_view` and not `MyTextView`. This has now been changed to `TextView` to ensure less breaking in the future and since only `text` was changed, this is enough.
This happened when viewing notes and causing configuration change or something else that would cause the state to be restored.

Fix crash when restoring state on TextFragment

---

app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/MainActivity.kt

Fixes #679
The problem occurred for all types of shortcuts, so this fix is for all of them.
**Before:**
https://github.com/SimpleMobileTools/Simple-Notes/assets/85929121/6d4f6064-10f8-4de3-8927-de94bfeeed00
**After:**
https://github.com/SimpleMobileTools/Simple-Notes/assets/85929121/4b229713-80ca-4087-b798-358ccb3b39e2

Fixed showing note picker on opening from shortcut (#679)
