app/src/main/res/values-hu/strings.xml
Translated strings.xml into Hungarian using the English version.
=> Hungarian translation of strings.xml

app/src/main/kotlin/com/simplemobiletools/notes/activities/MainActivity.kt, app/src/main/res/layout/activity_main.xml, app/src/main/res/menu/menu.xml
All functionality changes are in the first commit. Feel free to take just it if you don't like the style changes.
=> Remove fab

app/src/main/res/values-hu/strings.xml
Translated some new strings and fixed some old ones.
=> Update Hungarian translation

app/build.gradle, build.gradle
Targets SDK 26, Kotlin 1.1.2-5, Android Gradle Plugin 2.3.3
=> Update dependencies and SDKs

app/src/main/AndroidManifest.xml, app/src/main/kotlin/com/simplemobiletools/notes/activities/MainActivity.kt, app/src/main/kotlin/com/simplemobiletools/notes/helpers/Constants.kt
Allows to create a new note with given text from other apps with title set using a dialog.
=> Implement sharing to a new note (#56)

app/build.gradle, app/src/main/kotlin/com/simplemobiletools/notes/activities/MainActivity.kt, app/src/main/kotlin/com/simplemobiletools/notes/adapters/NotesPagerAdapter.kt, app/src/main/kotlin/com/simplemobiletools/notes/fragments/NoteFragment.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-lt/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values/strings.xml
Works as of now. Code needs some polishing, so it's WIP. I haven't decided what's the right name for a selection dialog yet, so I haven't created string resources for other languages.
=> Implement appending text received from external application

app/src/main/kotlin/com/simplemobiletools/notes/activities/SettingsActivity.kt, app/src/main/kotlin/com/simplemobiletools/notes/fragments/NoteFragment.kt, app/src/main/kotlin/com/simplemobiletools/notes/helpers/Config.kt, app/src/main/kotlin/com/simplemobiletools/notes/helpers/Constants.kt, app/src/main/res/layout/activity_settings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-lt/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values/strings.xml
By default cursor is placed to the end of note
=> Allow to choose whether to put cursor to end of note

app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-lt/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values/strings.xml
SimpleMobileTools/General-Discussion#33
=> Fix broken links in string resources comments

app/src/main/res/values-de/strings.xml
Translated the Play Store description to German and corrected some parts of the main translation.
=> update German translation

app/src/main/res/values-de/strings.xml
Forgot a period at the short description, fixed.
=> Tiny correction: German

app/src/main/res/values-pl/strings.xml
Hello!
The next update for Simple Mobile Tools 😊.
The best wishes,
Daria.
=> [Update] Polish translation

app/src/main/res/values-de/strings.xml
=> Improved German

app/src/main/res/values-zh-rCN/strings.xml
=> add chinese values

app/src/main/res/values-de/strings.xml
Latest German including changes for:
fb9479fdfcd20d27821a78ab150b47cfcb6d49a2
7f2c58eef8419438cf56e402998e32cdc9fcfc70
=> Push DE translation

app/src/main/res/values-da/strings.xml
=> New language!

app/src/main/res/values-gl/strings.xml
this is the first translation to galician (gl) of SimpleNotes
=> primeira tradución ao galego

app/src/main/res/values-fr/strings.xml
Hi, 
Here is an updated and fixed French translation.
=> Updated and made some fixes to the French translation

app/src/main/kotlin/com/simplemobiletools/notes/activities/MainActivity.kt, app/src/main/kotlin/com/simplemobiletools/notes/dialogs/ImportFolderDialog.kt, app/src/main/res/layout/dialog_import_folder.xml, app/src/main/res/menu/menu.xml, app/src/main/res/values-da/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-gl/strings.xml, app/src/main/res/values-hr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-lt/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
=> Import folder

app/src/main/res/values-pt-rBR/strings.xml
Local resource file strings.xml
=> PT-BR translation update [2018.06.21]

app/src/main/res/values-zh-rTW/strings.xml
I updated zh-rTW translations, please review and merge it :smiley:
=> Update zh-rTW translations.

app/src/main/res/values-pt-rBR/strings.xml
Now, it's have 78 chars. It's good? Please, review and let me know :D
=> update short description (pt-rBR)

app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/SettingsActivity.kt, app/src/main/kotlin/com/simplemobiletools/notes/pro/extensions/Context.kt, app/src/main/kotlin/com/simplemobiletools/notes/pro/fragments/TextFragment.kt, app/src/main/kotlin/com/simplemobiletools/notes/pro/helpers/Constants.kt
=> Font size settings changed to percentages

app/src/main/res/values-zh-rCN/strings.xml
As titled.
For the store description, it seems the 1st and last paragraph are repetitive. Thus left untranslated for now.
=> Updated zh_CN to cover all missing strings.

app/src/main/res/values-fr/strings.xml
As the title says, I only did some translations...
=> Updated French string.xml

app/src/main/res/values-it/strings.xml
See SimpleMobileTools/Simple-Music-Player#264 for more information.
=> translate app's descriptions in Italian

app/src/main/res/values-zh-rCN/strings.xml
=> Finish the remaining zh-CN translations

app/src/main/res/values-fa/strings.xml
add translate for app_long_description and faq_1_text
=> update persian language

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/MainActivity.kt, app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/WidgetConfigureActivity.kt, app/src/main/kotlin/com/simplemobiletools/notes/pro/fragments/NoteFragment.kt
=> Add support for locking with biometric ID

app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/MainActivity.kt
Hi,
I've fixed the wrong text in the import dialog. Functionality was working ok, only the text was wrong. Additionally, I've changed some consts in the import code, so they won't be misleading (export consts were used there).
**Before:**
https://user-images.githubusercontent.com/85929121/134708286-8aa16bcc-8285-4f4e-bb29-b21e12e26085.mp4
**After:**
https://user-images.githubusercontent.com/85929121/134708323-c4c7831e-83e4-4fb5-b1a8-4057980aaedb.mp4
=> Fixed text in import dialog (#436)

app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/SettingsActivity.kt, app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/WidgetConfigureActivity.kt, app/src/main/kotlin/com/simplemobiletools/notes/pro/adapters/WidgetAdapter.kt, app/src/main/res/layout/widget_text_layout.xml
Hi,
I've added monospaced font to widgets, so now the switch in settings also affects them.
https://user-images.githubusercontent.com/85929121/135323314-8d137cd3-d60e-4ca4-8c25-e4866cb22f2d.mp4
=> Added monospaced font to widgets (#292)

app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/MainActivity.kt
Closes #493
**Before:**
https://user-images.githubusercontent.com/85929121/150381544-d5e160c6-e43d-4924-a9f7-d4c364b67e07.mp4
**After:**
https://user-images.githubusercontent.com/85929121/150381643-c4e3a08d-7096-4b69-9dfb-533d32fc5f76.mp4
=> Prevented unnecessary save on undo/redo (#493)

app/src/main/kotlin/com/simplemobiletools/notes/pro/adapters/ChecklistAdapter.kt
Closes #499
**Before:**
https://user-images.githubusercontent.com/85929121/151342220-0aaa0a8d-52db-413d-ab91-d0d974746dd1.mp4
**After:**
https://user-images.githubusercontent.com/85929121/151342252-303b6eea-df51-428e-b2b8-a0e410dc6ba7.mp4
=> Added hiding checklist image on select to avoid item resizing (#499)

app/src/main/kotlin/com/simplemobiletools/notes/pro/adapters/WidgetAdapter.kt, app/src/main/res/layout/item_checklist_widget.xml
Fixes  #347
**Before:**
**After:**
=> Fixed text styling in checklist widget (#347)

app/src/main/res/values-vi/strings.xml
=> add vietnamese

app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/MainActivity.kt
Closes #576 
https://user-images.githubusercontent.com/85929121/208388957-1c234b11-05e1-4379-88be-5272d2cd5fa4.mp4
=> Added changing to previous note on deletion (#576)

app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/MainActivity.kt, app/src/main/res/drawable/ic_shortcut_icon.xml, app/src/main/res/drawable/shortcut_note.xml, app/src/main/res/menu/menu.xml
Closes #598
https://user-images.githubusercontent.com/85929121/222809357-7a3b9f07-c0cb-49b7-abc9-5f34d823ed4f.mp4
=> Added create shortcut option (#598)

app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/MainActivity.kt
hides keyboard while closing search bar
=> hide keyboard while closing search bar

app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/MainActivity.kt, app/src/main/kotlin/com/simplemobiletools/notes/pro/adapters/WidgetAdapter.kt
Closes #624
https://github.com/SimpleMobileTools/Simple-Notes/assets/85929121/9a45eb56-b20d-4df2-95f8-83c840aee9c8
=> Added sorting to the widget (#624)

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/SettingsActivity.kt, app/src/main/kotlin/com/simplemobiletools/notes/pro/dialogs/DateTimePatternInfoDialog.kt, app/src/main/kotlin/com/simplemobiletools/notes/pro/dialogs/ManageAutoBackupsDialog.kt, app/src/main/kotlin/com/simplemobiletools/notes/pro/extensions/Context.kt, app/src/main/kotlin/com/simplemobiletools/notes/pro/helpers/Constants.kt, app/src/main/kotlin/com/simplemobiletools/notes/pro/helpers/NotesHelper.kt, app/src/main/kotlin/com/simplemobiletools/notes/pro/receivers/AutomaticBackupReceiver.kt, app/src/main/kotlin/com/simplemobiletools/notes/pro/receivers/BootCompletedReceiver.kt, app/src/main/res/layout/activity_settings.xml, app/src/main/res/layout/datetime_pattern_info_layout.xml, app/src/main/res/layout/dialog_manage_automatic_backups.xml
Implemented the same way like in simple-contacts and simple-calendar
Close #364
=> Automatic backups

app/src/main/kotlin/com/simplemobiletools/notes/pro/activities/MainActivity.kt
=> Take all text scaling into account when determining pagerTabStrip height
